// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiPageWebApp.Models;

namespace MultiPageWebApp.Migrations
{
    [DbContext(typeof(ContactContext))]
    [Migration("20210208042909_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MultiPageWebApp.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            Address = "MAD Magazine, PO Box 8537, Big Sandy, TX 75755 - 853",
                            Name = "Alfred E Neuman",
                            Note = "Work",
                            Phone = "800-462-3624"
                        },
                        new
                        {
                            ContactId = 2,
                            Address = "BBC London, 2nd Floor, Peel Wing, BBC Broadcasting House, Portland Place, London, W1A 1AA",
                            Name = "Dwayne Dibbley",
                            Note = "Personal",
                            Phone = "020 8743 8000"
                        },
                        new
                        {
                            ContactId = 3,
                            Address = "1900 Broadway, (One Lincoln Plaza), New York, NY 10023",
                            Name = "Bert and Ernie",
                            Note = "Work",
                            Phone = "212-595-3456"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
